version: '3'

services:
  client:
    container_name: counter-client
    image: counter-client:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - '8080:8080'
    networks:
      - counter-app

networks:
  counter-app:
    driver: bridge
